version: '2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8081:8081
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx
        restart: always
 
    nrs-tutorijal6:
        depends_on:
            - reverseproxy
        image: "nrs-tutorijal6"
        ports:
            - 8001:8001
        restart: always
    
    getting-started:
        depends_on:
            - reverseproxy
        image: "getting-started"
        ports:
            - 3000:3000
        restart: always